version: '3'

services:
  db:
    image: mysql:5.7

    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

  todoback:
    image: node:14-alpine
    ports:
      - 3001
    depends_on:
      - "db"
    networks:
      - my-network

  todofront:
    image: node:14-alpine
    ports:
      - 3000
    depends_on:
      - "todoback"
    environment:
      REACT_APP_API_HOST: todoback
    networks:
      - my-network

  todotests:
    image: mjgargani/puppeteer:trybe1.0
    depends_on:
      - "todofront"
      - "todoback"
    environment:
      FRONT_HOST: todofront
    networks:
      - my-network

volumes:
  db-data:

networks:
  my-network: