version: '3'

services:
  todoback:
    image: node:14-alpine
    container_name: back_1
    ports:
      - 3001:3001
    volumes:
      - db-data:/var/lib/mysql
    depends_on:
      - "db"
    networks:
      - my-network
    environment:
      #MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  todofront:
    image: node:14-alpine
    #container_name: front_1
    ports:
      - 3000:3000
    depends_on:
      - "todoback"
    environment:
      REACT_APP_API_HOST: todoback
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - my-network

  todotests:
    image: mjgargani/puppeteer:trybe1.0
    #container_name: tests_1
    depends_on:
      - "todofront"
      - "todoback"
    environment:
      FRONT_HOST: todofront
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - my-network
  
  db:
    image: mysql:5.7
    #container_name: banco
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  db-data:

networks:
  my-network: